### PR TITLE
Lifecycle for scripts

### PR DESCRIPTION
**Pull request by truthfool**
- Added lifecycle for python installation scripts
- Added lifecycle for moving addons

### CODE REVIEW

**Comment by truthfool** [comment]
@SubhamPramanik @avikganguly01

**Comment by truthfool** [comment]
@avikganguly01 @SubhamPramanik

**Review by avikganguly01 — CHANGES_REQUESTED** [review]
Too many file changes. PR is unreviewable as it attempts to solve problems far beyond it's scope.

**Comment by truthfool** [comment]
Can you look into the last "lifecycle added" commit?

**Comment by jeremi** [comment]
If you really need to add the code of openg2p-erp, maybe add it as a submodule. It will be easier to maintain.

**Comment by truthfool** [comment]
@jeremi thanks . Finally, I was gonna use wget or git to download the openg2p modules.

**Pull request closed without merging**
